.TH "dht11_t" 3 "Sat Jul 27 2024" "Humedity and Temperature Sensing System Based in ESP32 Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dht11_t \- Structure containing readings and info about the dht11\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dht11_app\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdht11_pin\fP"
.br
.ti -1c
.RI "float \fBtemperature\fP"
.br
.ti -1c
.RI "float \fBhumidity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure containing readings and info about the dht11\&. 
.PP
Definition at line 16 of file dht11_app\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int dht11_pin"
ESP32 WROOM number pin to connect the dht11 data pin 
.PP
Definition at line 18 of file dht11_app\&.h\&.
.SS "float humidity"
variable to store the last humedity reading 
.br
 
.PP
Definition at line 20 of file dht11_app\&.h\&.
.SS "float temperature"
variable to store the last temperature reading 
.br
 
.PP
Definition at line 19 of file dht11_app\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Humedity and Temperature Sensing System Based in ESP32 Module from the source code\&.
