.TH "init_app" 3 "Sat Jul 27 2024" "Humedity and Temperature Sensing System Based in ESP32 Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
init_app \- Init_app
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBinit_app\&.h\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_devices\fP (void)"
.br
.RI "This function involves initialitation routines for devices as, LCD screen and its i2c comuniication protcol with the microcontroler\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "void init_devices (void)"

.PP
This function involves initialitation routines for devices as, LCD screen and its i2c comuniication protcol with the microcontroler\&. 
.PP
Definition at line 8 of file init_app\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Humedity and Temperature Sensing System Based in ESP32 Module from the source code\&.
