.TH "/home/nicolas/Documentos/especialidad_en_SE/2_arquitectura_2024_SE/lcd_hdt11_nico/main/devices/lcd_app.c" 3 "Sat Jul 27 2024" "Humedity and Temperature Sensing System Based in ESP32 Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nicolas/Documentos/especialidad_en_SE/2_arquitectura_2024_SE/lcd_hdt11_nico/main/devices/lcd_app.c
.SH SYNOPSIS
.br
.PP
\fC#include 'include/lcd_app\&.h'\fP
.br
\fC#include 'driver/i2c\&.h'\fP
.br
\fC#include 'unistd\&.h'\fP
.br
\fC#include 'esp_log\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlcd_init\fP (void)"
.br
.RI "This function calls inside initialitation functions for LCD and i2c comunication protcol\&. "
.ti -1c
.RI "void \fBlcd_send_cmd\fP (char cmd)"
.br
.RI "the function \fB\fBlcd_send_cmd()\fP\fP sends cpmmand to the LCD in 4 bits mode\&. "
.ti -1c
.RI "void \fBlcd_send_data\fP (char data)"
.br
.RI "the function \fB\fBlcd_send_data()\fP\fP sends data to the LCD in 4 bits mode\&. "
.ti -1c
.RI "void \fBlcd_put_cur\fP (int row, int col)"
.br
.RI "the function \fB\fBlcd_put_cur()\fP\fP lcd_put_cur is used to put the cursor at the respective location on the LCD\&. "
.ti -1c
.RI "void \fBlcd_send_string\fP (char *str)"
.br
.RI "lcd_send_string can be used to send a character string, or a buffer (containing characters) to the display\&. "
.ti -1c
.RI "void \fBlcd_clear\fP (void)"
.br
.RI "LCD 1602 have a command to clear the entire screen\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "esp_err_t \fBerr\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Humedity and Temperature Sensing System Based in ESP32 Module from the source code\&.
