.TH "startup_app" 3 "Sat Jul 27 2024" "Humedity and Temperature Sensing System Based in ESP32 Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
startup_app \- Startup_app
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBstartup_app\&.h\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBwelcome_message\fP (void)"
.br
.RI "This function shows on the LCD screen some general information as, project's name, project's author,and so on\&. "
.ti -1c
.RI "void \fBget_temp_humed\fP (void)"
.br
.RI "This function is inide of a while loop and shows on the LCD screen the temperature and humedity current values\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "void get_temp_humed (void)"

.PP
This function is inide of a while loop and shows on the LCD screen the temperature and humedity current values\&. 
.PP
Definition at line 38 of file startup_app\&.c\&.
.SS "void welcome_message (void)"

.PP
This function shows on the LCD screen some general information as, project's name, project's author,and so on\&. 
.PP
Definition at line 11 of file startup_app\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Humedity and Temperature Sensing System Based in ESP32 Module from the source code\&.
